import Head from 'next/head';

function NewPost() {
  return (
    <div>
      <Head>
        <title>Bloggo | new post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>New Post page</h1>
      </main>
    </div>
  );
}

export default NewPost;
