import Head from 'next/head';
import dynamic from 'next/dynamic'; // TO DO: is this actually necessary

const BlogEditor = dynamic(() => import('../../components/BlogEditor'), {
  ssr: false,
});

function NewPost() {
  return (
    <div className="bg-indigo-100">
      <Head>
        <title>Bloggo | new post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10 bg-indigo-100 h-full py-20">
        <h1 className="font-pathwayExtreme font-semibold text-2xl py-10">
          Create a new post with Bloggo
        </h1>
        {/* BLOG EDITOR - INTERACTIVE SECTION */}
        <BlogEditor />
      </main>
    </div>
  );
}

export default NewPost;
