import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className="w-screen">
      <Head>
        <title>Bloggo | write articles, posts, take notes...</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen bg-homepage pt-36 pl-20">
        <h1 className=" font-extrabold text-indigo-200 text-5xl font-pathwayExtreme">
          Welcome to Bloggo.
        </h1>
        <span className="flex w-full justify-start">
          <button className="mr-20 text-2xl mt-28  bg-indigo-200 p-3 font-pathwayExtreme font-semibold rounded-md hover:bg-indigo-300">
            Log in
          </button>
          <button className="text-2xl mt-28  bg-indigo-200 p-3 font-pathwayExtreme font-semibold rounded-md hover:bg-indigo-300">
            Find out more
          </button>
        </span>
      </main>

      {/* <footer className="bg-black">sss</footer> */}
    </div>
  );
};

export default Home;
