import type { NextPage } from 'next';
import Head from 'next/head';
// import Navbar from '../components/Navbar';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div className="w-screen">
      <Head>
        <title>Bloggo | write posts, articles, take notes...</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen bg-homepage pt-36 pl-20">
        <h1 className="font-bold text-indigo-200 text-6xl font-pathwayExtreme">
          Welcome to Bloggo.
        </h1>
        <span className="flex flex-col md:flex-row w-full justify-start">
          <button className="md:mr-20 w-2/3 md:w-60 text-2xl mt-28  bg-indigo-200 p-3 font-pathwayExtreme font-semibold rounded-md hover:bg-indigo-300">
            Log in
          </button>
          <button
            onClick={() => router.push('/posts/NewPost')}
            className="text-2xl w-2/3 md:w-60 mt-28  bg-indigo-200 p-3 font-pathwayExtreme font-semibold rounded-md hover:bg-indigo-300">
            Demo
          </button>
        </span>
      </main>

      {/* <footer className="bg-black">sss</footer> */}
    </div>
  );
};

export default Home;
