import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className="w-screen">
      <Head>
        <title>Bloggo | write articles, posts, take notes...</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-indigo-300 h-screen bg-homepage">
        <h1 className="font-semibold text-3xl font-sourceCodePro">
          Welcome to Bloggo.
        </h1>
      </main>

      {/* <footer className="bg-black">sss</footer> */}
    </div>
  );
};

export default Home;
